---
- hosts: localhost
  tasks:
    - include: tasks/core.yml  
    - include: tasks/apps.yml  
    - include: tasks/git.yml    
    - include: tasks/xcode.yml    
    - include: tasks/zsh.yml        
    - include: tasks/vscode.yml        
    - include: tasks/asdf.yml    
    - include: tasks/dotfiles.yml    