---
- hosts: localhost
  tasks:
    - include: tasks/core.yml
    - include: tasks/apps.yml
    - include: tasks/git.yml
    - include: tasks/xcode.yml
    - include: tasks/zsh.yml
    - include: tasks/asdf.yml
    - include: tasks/node.yml
    - include: tasks/java.yml
    - include: tasks/tmux.yml
    - include: tasks/dotfiles.yml
    - include: tasks/vscode.yml
