- git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "/Users/{{ lookup('env', 'USER') }}/.asdf"
    version: v0.9.0
  tags: asdf

- name: "Install asdf plugins"
  shell: |
    source /Users/{{ lookup('env', 'USER') }}/.asdf/asdf.sh
    asdf plugin-add {{ item }} || exit 0
  with_items:
    - nodejs
  tags: asdf

- name: "Install default node"
  shell: |
    source /Users/{{ lookup('env', 'USER') }}/.asdf/asdf.sh
    bash /Users/{{ lookup('env', 'USER') }}/.asdf/plugins/nodejs/bin/import-release-team-keyring
    asdf install nodejs 14.18.3
    asdf install nodejs 16.13.2
    asdf global nodejs 14.18.3