- name: Install homebrew
  include_role:
    name: geerlingguy.mac.homebrew
  tags: core

- name: Make sure homebrew bin is in path
  ansible.builtin.lineinfile:
    path: /etc/paths
    state: present
    line: "/opt/homebrew/bin"
  become: true
  become_user: root
  tags: core

- name: Add custom homebrew repos
  community.general.homebrew_tap:
    name: [homebrew/cask-versions, thoughtbot/formulae, weaveworks/tap, hashicorp/tap]
  tags: core

- name: Install homebrew packages
  community.general.homebrew:
    name:
      [
        "autoconf",
        "automake",
        "coreutils",
        "bundletool",
        "curl",
        "fzf",
        "gpg",
        "htop",
        "mas",
        "kubectx",
        "kubernetes-cli",
        "kubernetes-helm",
        "openssl",
        "thefuck",
        "tmux",
        "unzip",
        "vim",
        "jq",
        "neovim",
        "terraform",
        "zlib",
        "zsh",
        "hashicorp/tap/vault",
        "fastlane",
        "cocoapods",
        "betterdisplay"
      ]
    state: present
    update_homebrew: yes
  tags: core
