- name: Installing stow
  community.general.homebrew:
    name: ['stow']
    state: present
    update_homebrew: yes
      - install
      - dotfiles
      - stow

- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:ricca509/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - install
    - dotfiles
    - stow

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./install
  tags:
    - install
    - dotfiles
    - stow