- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:ricca509/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - install
    - dotfiles
    - stow

- name: Install dotfiles
  shell: cd $HOME/.dotfiles && ./install
  tags:
    - install
    - dotfiles
    - stow