
- name: "Install default node"
  shell: |
    source /Users/{{ lookup('env', 'USER') }}/.asdf/asdf.sh
    bash /Users/{{ lookup('env', 'USER') }}/.asdf/plugins/nodejs/bin/import-release-team-keyring
    asdf install nodejs 14.18.3
    asdf install nodejs 16.13.2
    asdf global nodejs 14.18.3
  tags: node